### ISSUE TITLE
Example problems hang inside initialize loop when run with MPI

### ISSUE THREAD

**Issue by benzwick** [mikaem/Oasis#25]
The DrivenCavity example runs fine in serial:
```
$ python NSfracStep.py problem=DrivenCavity
```
but when run with MPI:
```
$ mpirun -n 4 python NSfracStep.py problem=DrivenCavity
```
it hangs at the following line:
https://github.com/mikaem/Oasis/blob/3de552ca7271b0f91bed51322bab4fce06e63a99/oasis/problems/NSfracStep/DrivenCavity.py#L48

The following example problems have similar issues:

- Cylinder
- DrivenCavity3D
- TaylorGreen2D
- TaylorGreen3D

For example, TaylorGreen3D hangs here:
https://github.com/mikaem/Oasis/blob/3de552ca7271b0f91bed51322bab4fce06e63a99/oasis/problems/NSfracStep/TaylorGreen3D.py#L87

**Comment by mikaem** [comment]
I cannot reproduce this. Works fine for me on OSX, with fenics installed from conda-forge.

**Comment by benzwick** [comment]
Upgrading Python to 3.6.7 (from 3.5.3, the Debian Stretch 9.6 default) and reinstalling FEniCS 2018.1.0 from source with pybind11 version 2.2.3 also fixes this issue.
