### ISSUE TITLE
Running DrivenCavity, no time-series files created in folder time-series

### ISSUE THREAD

**Issue by Tom303-afk** [mikaem/Oasis#28]
Thank you for creating Oasis. I have installed fenics 2018.1 and oasis on ubuntu.
I tried running my first simulation with DrivenCavity.py. The simulation is running fine, a specific results-folder is created.
However, unfortunately the simulation does not create any files in the corresponding results-folder. The folder remains empty.
Do you have any suggested actions that I can do to fix this issue?

**Comment by mikaem** [comment]
Hi
There's a parameter 'save_step' that determines how often a snapshot is saved to file. For the 'DrivenCavity' demo it looks like this parameter is set too high and as such no files are stored. Use a smaller integer and the results should show up:-)

**Comment by Tom303-afk** [comment]
This was indeed the solution. Thank you for your swift and helpful response.
